### ISSUE TITLE
Uploading to Pico - missing rp2040load file

### ISSUE THREAD

**Issue by santaimpersonator** [arduino/ArduinoCore-mbed#207]
I installed the Arduino Core for the RP2040 through the board manager, but I am having issues uploading the blink sketch onto the board.

- I have installed the latest version available through the board manager:
    ![rp2040_installed](https://user-images.githubusercontent.com/36016723/115856551-e0d9a700-a3e9-11eb-8b45-d5034705a841.PNG)

- This is the current error output. The code compiles fine, there seems to be a `rp2040load` file/tool missing:
    ```
    Sketch uses 80072 bytes (0%) of program storage space. Maximum is 16777216 bytes.
    
    Global variables use 52920 bytes (19%) of dynamic memory, leaving 217416 bytes for local variables. Maximum is 270336 bytes.
    
    java.io.IOException: Cannot run program "C:\Users\<username>\Documents\ArduinoData\packages\arduino\tools\rp2040tools\1.0.2/rp2040load": CreateProcess error=2, The system cannot find the file specified
	    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	    at processing.app.helpers.ProcessUtils.exec(ProcessUtils.java:26)
	    at cc.arduino.packages.Uploader.executeUploadCommand(Uploader.java:129)
	    at cc.arduino.packages.uploaders.SerialUploader.runCommand(SerialUploader.java:383)
	    at cc.arduino.packages.uploaders.SerialUploader.uploadUsingPreferences(SerialUploader.java:197)
	    at cc.arduino.UploaderUtils.upload(UploaderUtils.java:77)
	    at processing.app.SketchController.upload(SketchController.java:732)
	    at processing.app.SketchController.exportApplet(SketchController.java:703)
	    at processing.app.Editor$UploadHandler.run(Editor.java:2055)
	    at java.lang.Thread.run(Thread.java:748)
    
    Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	    at java.lang.ProcessImpl.create(Native Method)
	    at java.lang.ProcessImpl.<init>(ProcessImpl.java:386)
	    at java.lang.ProcessImpl.start(ProcessImpl.java:137)
	    at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	    ... 9 more
    
    An error occurred while uploading the sketch
    ```

- I double checked for the `rp2040load` file/folder in the specified location:
    ![tools_folder](https://user-images.githubusercontent.com/36016723/115857519-0915d580-a3eb-11eb-938e-64d1f66cdec0.PNG)
    ![rp2040tools_folder](https://user-images.githubusercontent.com/36016723/115857534-0ca95c80-a3eb-11eb-9796-f980d950fba7.PNG)
    ![tools](https://user-images.githubusercontent.com/36016723/115857558-1206a700-a3eb-11eb-80c2-8adbb5b7f0ec.PNG)

- This is the full verbose text:
    - [verbose_output.txt](https://github.com/arduino/ArduinoCore-mbed/files/6364608/verbose_output.txt)

I did try to run the post install script, as mentioned in another issue https://github.com/arduino/ArduinoCore-mbed/issues/191#issuecomment-819279990. However, I ran the batch file instead of the shell script because I am working on a Windows 10 computer. Should I have run the shell script through WSL2 as well?

![batch_file](https://user-images.githubusercontent.com/36016723/115860368-9e669900-a3ee-11eb-8490-b01054cb1407.PNG)

Should I have manually installed the Arduino core with [these instructions](https://github.com/arduino/ArduinoCore-mbed#installation)?

**Comment by facchinm** [comment]
Hi @santaimpersonator ,
it looks like your antivirus got rid of `rp2040load`; we got some other similar reports and we are working to whitelist the file.
The repo is here https://github.com/arduino/rp2040tools in case you want to make sure it's not a virus :wink: 
To fix the situation you can temporarily download the windows binary from [here](https://github.com/arduino/rp2040tools/releases/download/1.0.3/rp2040tools-1.0.3-windows_386.tar.bz2) and extract it in `C:\Users\<username>\Documents\ArduinoData\packages\arduino\tools\rp2040tools\1.0.2` folder
